### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by franco876** [coomar2841/android-multipicker-library#10]
When use CameraImagePicker, create 3 files with different names like:
 .jpg 
-1.jpg 
-1-1.jpg

I think the problem is on generateFileName function

**Comment by coomar2841** [comment]
Checked this. Looks like it's working fine. Can you confirm if you are using the latest version?

**Comment by franco876** [comment]
I'm using latest version 0.9.7

The files are located on cacheLocation dir.

postProcess() function on FileProcessorThread is called 3 times for each file and generateFileName() function is generating a new name for each one.
I think you need to fix generateFileName() function

**Comment by coomar2841** [comment]
I am not able to reproduce this. Is it possible that while re-initializing you are passing a blank path? When your activity is getting killed?

**Comment by yilzer** [comment]
Hi, i was using this library too and get the same error. I think i found the bug, but i'm not sure if this is the right way to fix it. In FileProcessorThread OnRun() i removed this one:

    @Override
    public void run() {
        processFiles();
        //postProcessFiles();
        if (callback != null) {
            onDone();
        }
    }

and later you've to remove one line in  this method

    protected void processFiles() {

        ChosenFile file = files.get(0);
            try {
                file.setRequestId(requestId);
                Log.d(TAG, "processFile: Before: " + file.toString());
                processFile(file);
               // postProcess(file);
                file.setSuccess(true);
                Log.d(TAG, "processFile: Final Path: " + file.toString());
            } catch (PickerException e) {
                e.printStackTrace();
                file.setSuccess(false);
            }

    }

I think the main reason for this error is that VideoProcessorThread extends FileProcessorThread 
and in the onrun in videopreocessorthread the right path will be created. The other ones in FileProcessorThread are the double ones what causes the -1, -1-1. 

Please tell me if this is the right way to fix this bug. 
I implemented your library as module in my project

yilzer

**Comment by coomar2841** [comment]
Yes, you are right. There was a problem. The first line needs to be removed, but not the 2nd line. Fixing the 2nd part.

**Comment by coomar2841** [comment]
Try out `0.9.8`

**Comment by franco876** [comment]
Solved. Great work!! Thanks

**Comment by yilzer** [comment]
Solved man, Great work!
