### ISSUE TITLE
CacheLocation

### ISSUE THREAD

**Issue by robsonlira** [coomar2841/android-multipicker-library#115]
Hello!

In the getSavedCacheLocation method, the CacheLocation.EXTERNAL_STORAGE_PUBLIC_DIR option appears as deprecated.
I'm using the lib in a project with minSdkVersion 16 and targetSdkVersion 25
Is this a problem? because I notice that the camera files do not go to the sdcard

Obrigado!

**Comment by coomar2841** [comment]
You can still use this. But your app needs to have WRITE_EXTERNAL_STORAGE permission. If you are already handling runtime permissions for this, the app should work. But, ideally, you shouldn't be doing this.
