### ISSUE TITLE
Make picker classes non final for testability

### ISSUE THREAD

**Issue by gnumilanix** [coomar2841/android-multipicker-library#125]
We would like to be able to mock the result data when running the UI tests. But, since picker classes like `ImagePicker` and `CameraImagePicker` are final, we are not able to mock it with Mockito. Is there any chance for these classes to be defined non-final? So that it can be easily mocked?

On the side note, please continue to make `setImagePickerCallback` and `submit` to be non-final. I can make a pull request if help is needed.

**Comment by coomar2841** [comment]
You can create a pull request.

**Comment by gnumilanix** [comment]
@coomar2841 hope that helps. I have also written a sample on how we will use it to write tests in the PR.

**Comment by coomar2841** [comment]
Thanks. Closing this issue.
