### ISSUE TITLE
Fatal Exception: java.lang.NumberFormatException: For input string: 

### ISSUE THREAD

**Issue by vishrut2207** [coomar2841/android-multipicker-library#134]
Fatal Exception: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/ohmyprints-23032018-224632.jpg"
       at java.lang.Long.parseLong(Long.java:443)
       at java.lang.Long.valueOf(Long.java:542)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(Unknown Source)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(Unknown Source)
       at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(Unknown Source)

**Comment by vishrut2207** [comment]
I have the same problem and solved it.
I don't know it is the valid solution or not but try this.
I think it may work for you.

Replace
getAbsolutePathIfAvailable in FileProcessorThread
private ChosenFile getAbsolutePathIfAvailable(ChosenFile file) {

       String[] projection = {MediaStore.MediaColumns.DATA, MediaStore.MediaColumns.DISPLAY_NAME, MediaStore.MediaColumns.MIME_TYPE};

 // Workaround for various implementations for Google Photos/Picasa
       if (file.getQueryUri().startsWith("content://com.android.gallery3d.provider")) {
           file.setOriginalPath(Uri.parse(file.getQueryUri().replace("com.android.gallery3d", "com.google.android.gallery3d")).toString());
       } else {
           file.setOriginalPath(file.getQueryUri());
       }

       // Try to see if there's a cached local copy that is available
       if (file.getOriginalPath().startsWith("content://")) {
           try {
               Cursor cursor = context.getContentResolver().query(Uri.parse(file.getOriginalPath()), projection,
                       null, null, null);
               cursor.moveToFirst();
               try {
                   // Samsung Bug
                   if (!file.getOriginalPath().contains("com.sec.android.gallery3d.provider")) {
                       String path = cursor.getString(cursor
                               .getColumnIndexOrThrow(MediaStore.MediaColumns.DATA));
                       LogUtils.d(TAG, "processFile: Path: " + path);
                       if (path != null) {
                           file.setOriginalPath(path);
                       }
                   }
               } catch (Exception e) {
                   e.printStackTrace();
               }
               try {
                   String displayName = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.DISPLAY_NAME));
                   if (displayName != null) {
                       file.setDisplayName(displayName);
                   }
               } catch (Exception e) {
                   e.printStackTrace();
               }
               String mimeType = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.MIME_TYPE));
               if (mimeType != null) {
                   file.setMimeType(mimeType);
               }
               cursor.close();
           } catch (Exception e) {
               e.printStackTrace();
           }
       }

       if (!TextUtils.isEmpty(Uri.parse(file.getOriginalPath()).toString())) {
           if (!file.getQueryUri().contains("raw%")) {
               
               // Check if DownloadsDocument in which case, we can get the local copy by using the content provider
               if (file.getOriginalPath().startsWith("content:") && isDownloadsDocument(Uri.parse(file.getOriginalPath()))) {

                   if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                       String[] data = getPathAndMimeType(file);
                       if (data[0] != null) {
                           file.setOriginalPath(data[0]);
                       }
                       if (data[1] != null) {
                           file.setMimeType(data[1]);
                       }
                   }
               }

           }
       }
       return file;
   }

**Comment by fmagalhaes** [comment]
+1

**Comment by itsmasud** [comment]
> I have the same problem and solved it.
> I don't know it is the valid solution or not but try this.
> I think it may work for you.
> 
> Replace
> getAbsolutePathIfAvailable in FileProcessorThread
> 
> ```
> private ChosenFile getAbsolutePathIfAvailable(ChosenFile file) {
> 
>        String[] projection = {MediaStore.MediaColumns.DATA, MediaStore.MediaColumns.DISPLAY_NAME, MediaStore.MediaColumns.MIME_TYPE};
> 
>  // Workaround for various implementations for Google Photos/Picasa
>        if (file.getQueryUri().startsWith("content://com.android.gallery3d.provider")) {
>            file.setOriginalPath(Uri.parse(file.getQueryUri().replace("com.android.gallery3d", "com.google.android.gallery3d")).toString());
>        } else {
>            file.setOriginalPath(file.getQueryUri());
>        }
> 
>        // Try to see if there's a cached local copy that is available
>        if (file.getOriginalPath().startsWith("content://")) {
>            try {
>                Cursor cursor = context.getContentResolver().query(Uri.parse(file.getOriginalPath()), projection,
>                        null, null, null);
>                cursor.moveToFirst();
>                try {
>                    // Samsung Bug
>                    if (!file.getOriginalPath().contains("com.sec.android.gallery3d.provider")) {
>                        String path = cursor.getString(cursor
>                                .getColumnIndexOrThrow(MediaStore.MediaColumns.DATA));
>                        LogUtils.d(TAG, "processFile: Path: " + path);
>                        if (path != null) {
>                            file.setOriginalPath(path);
>                        }
>                    }
>                } catch (Exception e) {
>                    e.printStackTrace();
>                }
>                try {
>                    String displayName = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.DISPLAY_NAME));
>                    if (displayName != null) {
>                        file.setDisplayName(displayName);
>                    }
>                } catch (Exception e) {
>                    e.printStackTrace();
>                }
>                String mimeType = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.MIME_TYPE));
>                if (mimeType != null) {
>                    file.setMimeType(mimeType);
>                }
>                cursor.close();
>            } catch (Exception e) {
>                e.printStackTrace();
>            }
>        }
> 
>        if (!TextUtils.isEmpty(Uri.parse(file.getOriginalPath()).toString())) {
>            if (!file.getQueryUri().contains("raw%")) {
>                
>                // Check if DownloadsDocument in which case, we can get the local copy by using the content provider
>                if (file.getOriginalPath().startsWith("content:") && isDownloadsDocument(Uri.parse(file.getOriginalPath()))) {
> 
>                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
>                        String[] data = getPathAndMimeType(file);
>                        if (data[0] != null) {
>                            file.setOriginalPath(data[0]);
>                        }
>                        if (data[1] != null) {
>                            file.setMimeType(data[1]);
>                        }
>                    }
>                }
> 
>            }
>        }
>        return file;
>    }
> ```

I see there is no such code change with the latest repo. Probably your solution was accepted. But I am having the same issue.

**Comment by coomar2841** [comment]
This should be fixed in 1.6. Please re-open if issue exists.
