### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by hatpick** [coomar2841/android-multipicker-library#14]
How can I have a picker for mime type: PDF on all APIs. I'm using application/pdf and it works on api 21+. What about pr-lollipop? is it supported at all?

**Comment by coomar2841** [comment]
I haven't tried that, but I think I can add a method which takes in the mimetype so that you can trigger PDF picker. I cannot guarantee that it works on all OSes and phones. But, I think it's a good to have addon.

**Comment by coomar2841** [comment]
Done. will be release with `v1.0.11`.
