### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by virengujariya** [coomar2841/android-multipicker-library#140]
```
Fatal Exception: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/2612078_L.jpg"
       at java.lang.Long.parseLong(Long.java:590)
       at java.lang.Long.valueOf(Long.java:804)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:367)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(FileProcessorThread.java:343)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:169)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)
```

Mostly issue for Android OS 8, library version 1.1.31

**Comment by vishrut2207** [comment]
I have the same problem and solved it.
I don't know it is the valid solution or not but try this. 
I think it may work for you.

Replace 
**getAbsolutePathIfAvailable** in FileProcessorThread

 private ChosenFile getAbsolutePathIfAvailable(ChosenFile file) {
        String[] projection = {MediaStore.MediaColumns.DATA, MediaStore.MediaColumns.DISPLAY_NAME, MediaStore.MediaColumns.MIME_TYPE};

        // Workaround for various implementations for Google Photos/Picasa
        if (file.getQueryUri().startsWith("content://com.android.gallery3d.provider")) {
            file.setOriginalPath(Uri.parse(file.getQueryUri().replace("com.android.gallery3d", "com.google.android.gallery3d")).toString());
        } else {
            file.setOriginalPath(file.getQueryUri());
        }

        // Try to see if there's a cached local copy that is available
        if (file.getOriginalPath().startsWith("content://")) {
            try {
                Cursor cursor = context.getContentResolver().query(Uri.parse(file.getOriginalPath()), projection,
                        null, null, null);
                cursor.moveToFirst();
                try {
                    // Samsung Bug
                    if (!file.getOriginalPath().contains("com.sec.android.gallery3d.provider")) {
                        String path = cursor.getString(cursor
                                .getColumnIndexOrThrow(MediaStore.MediaColumns.DATA));
                        LogUtils.d(TAG, "processFile: Path: " + path);
                        if (path != null) {
                            file.setOriginalPath(path);
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                try {
                    String displayName = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.DISPLAY_NAME));
                    if (displayName != null) {
                        file.setDisplayName(displayName);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                String mimeType = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.MIME_TYPE));
                if (mimeType != null) {
                    file.setMimeType(mimeType);
                }
                cursor.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        if (!TextUtils.isEmpty(Uri.parse(file.getOriginalPath()).toString())) {
            if (!file.getQueryUri().contains("raw%")) {
                
                // Check if DownloadsDocument in which case, we can get the local copy by using the content provider
                if (file.getOriginalPath().startsWith("content:") && isDownloadsDocument(Uri.parse(file.getOriginalPath()))) {

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                        String[] data = getPathAndMimeType(file);
                        if (data[0] != null) {
                            file.setOriginalPath(data[0]);
                        }
                        if (data[1] != null) {
                            file.setMimeType(data[1]);
                        }
                    }
                }

            }
        }

        return file;
    }

**Comment by coomar2841** [comment]
Need to look into this.

**Comment by fmagalhaes** [comment]
+1

**Comment by itsmasud** [comment]
> I have the same problem and solved it.
> I don't know it is the valid solution or not but try this.
> I think it may work for you.
> 
> ## Replace
> **getAbsolutePathIfAvailable** in FileProcessorThread
> ```
> private ChosenFile getAbsolutePathIfAvailable(ChosenFile file) {
> 
>        String[] projection = {MediaStore.MediaColumns.DATA, MediaStore.MediaColumns.DISPLAY_NAME, MediaStore.MediaColumns.MIME_TYPE};
> 
>  // Workaround for various implementations for Google Photos/Picasa
>        if (file.getQueryUri().startsWith("content://com.android.gallery3d.provider")) {
>            file.setOriginalPath(Uri.parse(file.getQueryUri().replace("com.android.gallery3d", "com.google.android.gallery3d")).toString());
>        } else {
>            file.setOriginalPath(file.getQueryUri());
>        }
> 
>        // Try to see if there's a cached local copy that is available
>        if (file.getOriginalPath().startsWith("content://")) {
>            try {
>                Cursor cursor = context.getContentResolver().query(Uri.parse(file.getOriginalPath()), projection,
>                        null, null, null);
>                cursor.moveToFirst();
>                try {
>                    // Samsung Bug
>                    if (!file.getOriginalPath().contains("com.sec.android.gallery3d.provider")) {
>                        String path = cursor.getString(cursor
>                                .getColumnIndexOrThrow(MediaStore.MediaColumns.DATA));
>                        LogUtils.d(TAG, "processFile: Path: " + path);
>                        if (path != null) {
>                            file.setOriginalPath(path);
>                        }
>                    }
>                } catch (Exception e) {
>                    e.printStackTrace();
>                }
>                try {
>                    String displayName = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.DISPLAY_NAME));
>                    if (displayName != null) {
>                        file.setDisplayName(displayName);
>                    }
>                } catch (Exception e) {
>                    e.printStackTrace();
>                }
>                String mimeType = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.MIME_TYPE));
>                if (mimeType != null) {
>                    file.setMimeType(mimeType);
>                }
>                cursor.close();
>            } catch (Exception e) {
>                e.printStackTrace();
>            }
>        }
> 
>        if (!TextUtils.isEmpty(Uri.parse(file.getOriginalPath()).toString())) {
>            if (!file.getQueryUri().contains("raw%")) {
>                
>                // Check if DownloadsDocument in which case, we can get the local copy by using the content provider
>                if (file.getOriginalPath().startsWith("content:") && isDownloadsDocument(Uri.parse(file.getOriginalPath()))) {
> 
>                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
>                        String[] data = getPathAndMimeType(file);
>                        if (data[0] != null) {
>                            file.setOriginalPath(data[0]);
>                        }
>                        if (data[1] != null) {
>                            file.setMimeType(data[1]);
>                        }
>                    }
>                }
> 
>            }
>        }
> 
>        return file;
>    }
> ```

There is no such change with your solution comparing with the latest repo. And I am having the same issue.
So this issue exists in the current repo.

**Comment by coomar2841** [comment]
This should be fixed. Please check with 1.6. Re-open if the issue exists.
