### ISSUE TITLE
imgCameraPicker Files cannot be uploaded

### ISSUE THREAD

**Issue by icangku** [coomar2841/android-multipicker-library#148]
I've done something the same as videoCameraPicker's code, but when I do uploading,  images that are taken from the camera not uploaded to a server but videos that are taken from the camera uploaded very well, anyone can help me?

It's actually like the original path not showing real path, because if I see to the gallery there's no file name like getOriginalPath

**Comment by coomar2841** [comment]
Can you post some logs?

**Comment by icangku** [comment]
Its solved, thanks for helping
