### ISSUE TITLE
How to create Chosen Image Object from a path ?

### ISSUE THREAD

**Issue by icangku** [coomar2841/android-multipicker-library#152]
How to create Chosen Image Object from a path? I have able to show images with List<ChosenImage>, but now I want to let the user edit the List<ChosenImage> with the paths that I've stored in a database, how to do this?

**Comment by icangku** [comment]
help me

**Comment by icangku** [comment]
help me

**Comment by coomar2841** [comment]
Why would you need this? Can you share an example or a scenario?

**Comment by icangku** [comment]
I've done this, I use File to do my thing not using ChosenImage obj
