### ISSUE TITLE
ERROR: Failed to resolve: com.kbeanie:multipicker:1.6

### ISSUE THREAD

**Issue by lovely-karn** [coomar2841/android-multipicker-library#154]
Getting error with 1.6 version. Unable to resolve.

**Comment by itsmasud** [comment]
Yeah, the workaround is to use 1.5. This will serve your purpose.

**Comment by deepbhavsar** [comment]
@itsmasud 
I am facing same problem.
Failed to resolve: com.kbeanie:multipicker:1.6

**Comment by coomar2841** [comment]
1.6 version is released.
