### ISSUE TITLE
Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)

### ISSUE THREAD

**Issue by Sunaina015** [coomar2841/android-multipicker-library#162]
I am getting this error when i am going to upload the image in android version 8.0 to above.
Please help me how we can resolve this issue.

**Comment by coomar2841** [comment]
This doesn't look like a library issue. Are you using a service to upload the image? You can refer to the above documentation for correctly implementing such a service.
