### ISSUE TITLE
Photo directory

### ISSUE THREAD

**Issue by sandeshlasnapure** [coomar2841/android-multipicker-library#19]
Showing directory containing image with scaled with original image.
app name/appname_pictures(path of directory).
cameraPickerProfile.shouldGenerateMetadata(false);
cameraPickerProfile.shouldGenerateThumbnails(false);
after setting above lines still generating folder .
Is there any another way to stop creating the folder.

**Comment by coomar2841** [comment]
Setting these value as false, will still create directories. The thumbnails and other metadata won't be generated.

**Comment by sandeshlasnapure** [comment]
Its still creating the thumbnails. And one single image has three copies.

**Comment by sandeshlasnapure** [comment]
This issue is solved after updating to 0.9.9.
