### ISSUE TITLE
Exif issue

### ISSUE THREAD

**Issue by CorentinPacaud** [coomar2841/android-multipicker-library#20]
Code :
```
            mCameraImagePicker = new CameraImagePicker(activity);
            mCameraImagePicker.shouldGenerateMetadata(true);
            mCameraImagePicker.shouldGenerateThumbnails(false);
            mCameraImagePicker.ensureMaxSize(1920, 1920);
            mCameraImagePicker.setImagePickerCallback(this);
```

This line in particular :
```
            mCameraImagePicker.ensureMaxSize(1920, 1920);
```
has an issue : I think it doesn't copy the exif params into the reiszed file.  All your resized file don't have exif (or change orientation before saving).
So, Glide can't orientate it correctly

To help : http://stackoverflow.com/questions/13596500/android-image-resizing-and-preserving-exif-data-orientation-rotation-etc

We also do something which can help you : 
``` 
public static Bitmap getResizedBitmap(Bitmap bm, int newWidth, int newHeight) {
        int width = bm.getWidth();
        int height = bm.getHeight();
        float scaleWidth = ((float) newWidth) / width;
        float scaleHeight = ((float) newHeight) / height;
        // CREATE A MATRIX FOR THE MANIPULATION
        Matrix matrix = new Matrix();
        // RESIZE THE BIT MAP
        matrix.postScale(scaleWidth, scaleHeight);

        // RECREATE THE NEW BITMAP
        Bitmap resizedBitmap;
        try {
            resizedBitmap = Bitmap.createBitmap(
                    bm, 0, 0, width, height, matrix, false);
        } catch (OutOfMemoryError error) {
            // do something
        }
        return resizedBitmap;
    }```

**Comment by coomar2841** [comment]
Thanks. Will fix this.

**Comment by Toolenaar** [comment]
I have a similar issue. But im not sure it is caused by this. All Images I take with my phone (Samsung galaxy s6) are landscape, even the portrait once. However in the photo gallery app they show correctly. When getting the exif data the orientation always returns 0. Has this to do with this bug or is it something else.

**Comment by usmaanz** [comment]
I am getting the exact same behaviour as @Toolenaar. 

@coomar2841 This still seems to be an issue.
