### ISSUE TITLE
Camera Path cannot be null. Re-initialize with correct path value.

### ISSUE THREAD

**Issue by sandeshlasnapure** [coomar2841/android-multipicker-library#21]
Updating to 0.9.9 getting this error for camera capture. on Samsung S4. I have followed the wiki for creating the picker.

**Comment by coomar2841** [comment]
<pre>
@Override
    protected void onSaveInstanceState(Bundle outState) {
        // You have to save path in case your activity is killed.
        // In such a scenario, you will need to re-initialize the CameraImagePicker
        outState.putString("picker_path", outputPath);
        super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        // After Activity recreate, you need to re-initialize these
        // two values to be able to re-initialize CameraImagePicker
        if (savedInstanceState != null) {
            if (savedInstanceState.containsKey("picker_path")) {
                outputPath = savedInstanceState.getString("picker_path");
            }
        }
        super.onRestoreInstanceState(savedInstanceState);
    }
</pre>

Can you check when you are reinitializing, the path is not null?

**Comment by sandeshlasnapure** [comment]
I have done the same thing
@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putString(PROFILE_PATH_KEY, profileImagePath);
        outState.putString(COVER_PATH_KEY, coverImagePath);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        if (savedInstanceState != null) {
            if (savedInstanceState.containsKey(PROFILE_PATH_KEY)) {
                profileImagePath = savedInstanceState.getString(PROFILE_PATH_KEY);
                if (!Utility.isEmpty(profileImagePath)) {
                    Glide.with(ReviewProfile.this).load(profileImagePath).fitCenter().signature(new StringSignature(profileImagePath + System.currentTimeMillis())).override(120, 120).bitmapTransform(new CropCircleTransformation(ReviewProfile.this)).diskCacheStrategy(DiskCacheStrategy.RESULT).into(profileImage);
                }

            }
            if (savedInstanceState.containsKey(COVER_PATH_KEY)) {
                coverImagePath = savedInstanceState.getString(COVER_PATH_KEY);
                toggleImageButtonView(coverImagePath);
                if (!Utility.isEmpty(coverImagePath)) {
                    Glide.with(ReviewProfile.this).load(coverImagePath).fitCenter().signature(new StringSignature(coverImagePath + System.currentTimeMillis())).bitmapTransform(new RoundedCornersTransformation(ReviewProfile.this, 30, 2)).diskCacheStrategy(DiskCacheStrategy.RESULT).into(coverPic);
                }
            }
        }
    }

**Comment by sandeshlasnapure** [comment]
Code in activity result

if (cameraPickerProfile == null) {
                        cameraPickerProfile = new CameraImagePicker(this);
                        cameraPickerProfile.setImagePickerCallback(profilePictureImageChosen);
                        cameraPickerProfile.setRequestId(requestCode);
                        cameraPickerProfile.shouldGenerateThumbnails(false);
                        cameraPickerProfile.shouldGenerateMetadata(false);
                        cameraPickerProfile.reinitialize(profileImagePath);
                    }
                    cameraPickerProfile.submit(data);

**Comment by sandeshlasnapure** [comment]
got the issue there was mis match with path.

**Comment by karumanchideepa** [comment]
Hi i am facing this issue when we are capturing the image from camera 

Unable to resume activity 
Failure delivering result ResultInfo{who=null, request=4222, result=-1, data=Intent { act=android.media.action.IMAGE_CAPTURE dat=file:///storage/emulated/0/imagepicker/imagepicker Pictures/870f32da-d44a-42d4-946b-dc06e9dcc39f.jpeg (has extras) }} to activity {com.outthinking.imageblur/com.outthinking.imageblur.LaunchActivity}:

 java.lang.RuntimeException: Camera Path cannot be null. Re-initialize with correct path value.

**Comment by sregg** [comment]
I'm seeing the same thing now as well.
I'm pretty sure it was still working fine a few weeks ago.
The only thing that changed since then that I can think of is that I update to Android 7.1.2.
