### ISSUE TITLE
Type-o in Picking-Images wiki

### ISSUE THREAD

**Issue by Toolenaar** [coomar2841/android-multipicker-library#23]
Small thing but I thought I should mention it.
On https://github.com/coomar2841/android-multipicker-library/wiki/2.-Picking-Images
there is a type in the OnActivityResult for the cameraPicker

`if(requestCode == Picker.PICK_IMAGE_DEVICE) {`

should be

`if(requestCode == Picker.PICK_IMAGE_CAMERA) {`

**Comment by coomar2841** [comment]
Thanks. Fixed. :)
