### ISSUE TITLE
Compatibility Doubt

### ISSUE THREAD

**Issue by renanbandeira** [coomar2841/android-multipicker-library#28]
First of all, I'm sorry for creating this as an issue, but I couldn't find better way to do it.

So, I will use this lib on my project, I liked a lot! But I have one question:
**Does anyone have a list of compatible devices for the camera and gallery feature?**

It would be great for my tests documentation if there is a list.

Thanks in advance

**Comment by coomar2841** [comment]
There's no list, and you should expect this to work on all devices. If it doesn't work on any device/os, it's a bug, and should be fixed when reported.

**Comment by renanbandeira** [comment]
Nice, thanks!
