### ISSUE TITLE
How can i disable get image from bing ? 

### ISSUE THREAD

**Issue by erhanharm** [coomar2841/android-multipicker-library#30]
Hello,

THANKS for this library i want to user this in my App   OTODYO!

How can i disable get image from bing ?

**Comment by coomar2841** [comment]
It shouldn't show up if you don't have the sample app installed. Please check if you have the sample app installed. Uninstall this and verify again.

**Comment by erhanharm** [comment]
Thanks a lot,

ıt works ;)


On Mon, May 30, 2016 at 12:06 PM, Kumar Bibek <notifications@github.com>
wrote:

> It shouldn't show up if you don't have the sample app installed. Please
> check if you have the sample app installed. Uninstall this and verify again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coomar2841/android-multipicker-library/issues/30#issuecomment-222447914>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAL1Jk3dXewZbBqm200A8Aee7TVR2d4Qks5qGqiUgaJpZM4IpQop>
> .
>



-- 
*Erhan Harmankaya*

http://tr.linkedin.com/in/erhanharmankaya
