### ISSUE TITLE
Open camera app directly

### ISSUE THREAD

**Issue by MrBrightside29** [coomar2841/android-multipicker-library#33]
Hi,

First, congrats for the library! It is very complete and helpfull!
My question is if it is possible to bypass the camera app selection intent and open it directly if the camera picker has been selected. Just like Telegram and Whatsapp do.

Thanks!

**Comment by coomar2841** [comment]
That's not possible with the approach that this library takes. Whatsapp does prompt for camera selection at least on my phone. Don't know about telegram.

**Comment by MrBrightside29** [comment]
Maybe is because of you have more than one camera app. In my case with just the default one, does not prompt.

**Comment by coomar2841** [comment]
Oh Ok. Got your point. Yes, that can be done.

**Comment by coomar2841** [comment]
Will be released with `v1.1.1`
