### ISSUE TITLE
Its not working on device without sd card????

### ISSUE THREAD

**Issue by saurabh810** [coomar2841/android-multipicker-library#35]
Its not working on device without sd card. Even after changing temp storage by using CacheLocation its still not working.

**Comment by coomar2841** [comment]
Can you post some logs and code snippets?

**Comment by coomar2841** [comment]
Oh, you are right. The one with the internal storage option is not released yet. For some reason, I missed it. Will be releasing it soon.

**Comment by tree1891** [comment]
so how to do on device without sd card?

**Comment by coomar2841** [comment]
You can choose CacheLocation to internal storage.
