### ISSUE TITLE
Save selected image to custom path and rename it!

### ISSUE THREAD

**Issue by masoudltf** [coomar2841/android-multipicker-library#37]
Hi, can i save image in custom path like "/storage/emulated/0/CustomFolder/CustomName" ?

**Comment by coomar2841** [comment]
It's not possible as of now, but I can work on this.

**Comment by masoudltf** [comment]
thanks.

**Comment by coomar2841** [comment]
Added an option to set custom folder name. (Top Level). Will be released in 1.1.2

**Comment by coomar2841** [comment]
Please open a new issue if you want the file name configurable, since it's a bit tricky for now.
