### ISSUE TITLE
allowMultiple() is not working

### ISSUE THREAD

**Issue by dev4ce** [coomar2841/android-multipicker-library#39]
After setting allowMultiple(), it just allows to select single image. Not get anything in log too.
code for imagepicker is as follows:

imagePicker = new ImagePicker(MainActivity.this);
        imagePickerCallback = new ImagePickerCallback() {
            @Override
            public void onImagesChosen(List<ChosenImage> images) {
            }

            @Override
            public void onError(String message) {
            }
        };
        imagePicker.setImagePickerCallback(imagePickerCallback);
        imagePicker.allowMultiple();

**Comment by mahesh825mahi** [comment]
Is it working fine ?

**Comment by coomar2841** [comment]
Which application are you using to choose the image?

**Comment by dev4ce** [comment]
I'm using Gallery App.

**Comment by coomar2841** [comment]
While in the gallery app, to trigger multiple selections, you have to long press on the first image, and then multi-selection will be triggered. Let me know if that works. Also, have you tried with the sample app?

**Comment by sandeshlasnapure** [comment]
still having the same problem.

**Comment by DrewCarlson** [comment]
@sandeshlasnapure Can you provide more detail, what device and gallery application are experiencing issues?  I am not seeing any cases where multi selection does not work (except galleries that don't actually support it.)

**Comment by dev4ce** [comment]
As @coomar2841  rightly suggested, it was gallery specific. It's not an issue anymore for me. Thanks guys.
