### ISSUE TITLE
Custom request code for Intent

### ISSUE THREAD

**Issue by SandeshPrcvSoft** [coomar2841/android-multipicker-library#4]
Hi, 
I have an Activity with three buttons I just want to handle captured events for each button.
But am anot able to set request code. And am getting request code same for every click though I have created seperate ImagePicker and their callback. So how can I handle seperate three imagePicker callback.

Thanks

**Comment by coomar2841** [comment]
Good point. Will work on it.

**Comment by coomar2841** [comment]
Sorry, but thinking a bit harder, I am not sure why would you need that. At any time, you will be tapping on a single button, right?

**Comment by SandeshPrcvSoft** [comment]
Hi,
Thanks for you reply. I have following conditions, 

I have three different buttons and each has its own dedicated image view so thats why I need to handle each callback for each button. But there is no way to differentiate the callbacks the only way for as of now that passing the request code, but seems like there is no way to pass my own request code.
And this is one of the best picker library  have seen so far, because I am getting whole lot picker functionality in just one library. So there will be no more dependency in my gradle file.
Its quick and responsive.
Except 
1. Missing progaurd rules
2. Configuration like other image picker library offers like Ted picket and Easy image picker.(storage,folder and image name)

Thanks and any help on this will be really appreciated.
Let me know in case of any concern. 

Thanks, 
Sandesh

**Comment by coomar2841** [comment]
Would it help if I add a `setRequestId(int id)` method to the `ImagePicker` for example, and on the `ChosenFile` would have this value?

**Comment by SandeshPrcvSoft** [comment]
Yes that might the one of option.
And can also be handled by its own picker instance, like
Picker picker_one = new Picker ();
picker_one.callback_one(new callback);
Picker picker_two = new Picker ();
picker_two.callback_two(new callback);

And any distinguishable object must pass to on imagechosen callback.
So that we can implement only one listner
which will be having some sort of specific id for specific call so that developer can handle callback for specific button.
Which one do you think would be efficient way please let me know. 

Thanks,
Sandesh

**Comment by coomar2841** [comment]
The first option might be a lengthy one to implement. So, I think I would go with the 2nd option. I will add this feature.

**Comment by coomar2841** [comment]
Also, for the proguard settings, is it failing right now? I don't see a reason why it would need extra proguard rules to make it work.

As for the folder names, if you use `CacheLocation.EXTERNAL_STORAGE_PUBLIC_DIR`, you do get application specific directories already.

**Comment by SandeshPrcvSoft** [comment]
Thanks for the guidance. Waiting for the feature.

**Comment by coomar2841** [comment]
Done. It should be available in 1-2 hours on maven. 0.9.6.

**Comment by SandeshPrcvSoft** [comment]
Choose select multiple images not working on samsung galaxy s4

**Comment by coomar2841** [comment]
Which app you are checking? The default gallery app?

**Comment by SandeshPrcvSoft** [comment]
I am checking the demo you have uploaded on play store.

**Comment by coomar2841** [comment]
Please create a separate issue for this.
