### ISSUE TITLE
How can set compression level (image quality) and extension like: png, etc?

### ISSUE THREAD

**Issue by Celggar** [coomar2841/android-multipicker-library#47]
It would be great if I could explain how to do this. if the library does not support it I think it would be a great addition.
Thanks for your great effort and sorry for the trouble.

**Comment by coomar2841** [comment]
Will take this as a feature request for a later version.

**Comment by umesh0492** [comment]
@Ceaggar  

        try {
            FileOutputStream fos = new FileOutputStream (pictureFile); //takes a output file as input
            image.compress (Bitmap.CompressFormat.WEBP, 75, fos); //image is a bitmap type variable
            fos.close ();

        } catch (FileNotFoundException e) {
        } catch (IOException e) {
        }

**Comment by coomar2841** [comment]
Released with v1.5
