### ISSUE TITLE
Provider Conflict

### ISSUE THREAD

**Issue by ldemay** [coomar2841/android-multipicker-library#48]
`com.android.server.pm.PackageManagerException: Can't install because provider name com.kbeanie.multipicker (in package package.name.A) is already used by package.name.B`

Using com.kbeanie:multipicker:1.1.2-beta@aar

**Comment by coomar2841** [comment]
WIll work on it. Thanks.

**Comment by coomar2841** [comment]
Can you try this version?

```com.kbeanie:multipicker:1.1.21-beta@aar```

**Comment by ldemay** [comment]
Checked with 2 Nexus 5x, 6.0.1 and 7.0, all good!
Thanks

**Comment by coomar2841** [comment]
(y)

**Comment by coomar2841** [comment]
Closing this. Will make a final release sometime this week.
