### ISSUE TITLE
Pick Image from gallery

### ISSUE THREAD

**Issue by SandeshPrcvSoft** [coomar2841/android-multipicker-library#5]
Custom request code with camera picker works fine. but
setting custom request code for gallery pick am not getting that request code in onActivityResult.

**Comment by SandeshPrcvSoft** [comment]
I am getting default 3111 request code every time for gallery pick.

**Comment by coomar2841** [comment]
Request code will be same.. But, each objects requestId will be what you have set. Can you verify once?

**Comment by SandeshPrcvSoft** [comment]
I didn't get you.

**Comment by SandeshPrcvSoft** [comment]
Yes you are right. Got the point.
Am getting my request id with ChosenImage object from the list.
ChosenImage chosenImage = list.get(position);
chosenImage.getRequestId();
Thanks

**Comment by SandeshPrcvSoft** [comment]
Finally I have done something like this 
 if (requestCode == Picker.PICK_IMAGE_DEVICE) {
                if (imagePicker1 == null) {
                    imagePicker1 = new ImagePicker(this);
                    imagePicker1.setImagePickerCallback(this);
                }
                imagePicker1.submit(data);
            } else if (requestCode == CAMERA_CAPTURE_CODE_ONE) {
                if (cameraPicker1 == null) {
                    cameraPicker1 = new CameraImagePicker(this);
                    cameraPicker1.setImagePickerCallback(cameraPicker1ImageChosen);
                    cameraPicker1.setRequestId(requestCode);
                    cameraPicker1.reinitialize(path);
                }
                cameraPicker1.submit(data);
            } else if (requestCode == CAMERA_CAPTURE_CODE_TWO) {
                if (cameraPicker2 == null) {
                    cameraPicker2 = new CameraImagePicker(this);
                    cameraPicker2.setImagePickerCallback(coverPicture2ImageChosen);
                    cameraPicker2.reinitialize(profileImagePath);
                }
                cameraPicker2.submit(data);
            }
Reason :- some times getting 0 request id in object
Please correct me if am wrong.

**Comment by coomar2841** [comment]
You will get request ID as zero, if you haven't set a request ID.
