### ISSUE TITLE
Captured file extension is wrong (missing the dot separator)

### ISSUE THREAD

**Issue by livotov** [coomar2841/android-multipicker-library#52]
This produces files like 8e40c115-c123-44bd-9905-96a80beb2241jpeg, should be 8e40c115-c123-44bd-9905-96a80beb2241.jpeg or 8e40c115-c123-44bd-9905-96a80beb2241.jpg

**Comment by livotov** [comment]
added fix into my pull request for #46 too.

**Comment by coomar2841** [comment]
Thanks :)


*Thanks and Regards,Kumar Bibek*


*http://techdroid.kbeanie.com
<http://techdroid.kbeanie.com>http://www.kbeanie.com
<http://www.kbeanie.com>*
