### ISSUE TITLE
resultCode always return RESULT_CANCELED when configure CameraImagePicker to use internal app directory

### ISSUE THREAD

**Issue by iori57** [coomar2841/android-multipicker-library#55]
If you use CameraImagePicker and configure it to use internal app directory such as below:

```
mCameraImagePicker = new CameraImagePicker(this);
mCameraImagePicker.setImagePickerCallback(getImagePickerCallback());
mCameraImagePicker.setCacheLocation(CacheLocation.INTERNAL_APP_DIR);
mCameraImagePicker.pickImage();
```

In onActivityResult, it always return RESULT_CANCELED after taking a photo, tried this on default camera app and also third party camera app.

Using ImagePicker doesn't have this issue.

For the mean time I am using CacheLocation.EXTERNAL_CACHE_DIR for it to work :)

I am using official released version 1.1.1 by the way.

Thanks!

**Comment by coomar2841** [comment]
This is a limitation. Will add some checks in the library to prevent this. May be throw an exception. While dealing with Camera for taking pictures or videos, you can't use the Internal App Directory with this library.

**Comment by GuillaumeDelente** [comment]
@coomar2841 just for reference, why is `INTERNAL_APP_DIR` incompatible with taking pictures/videos?
