### ISSUE TITLE
If use ensureMaxSize with CameraImagePicker, unable to delete original photo

### ISSUE THREAD

**Issue by iori57** [coomar2841/android-multipicker-library#56]
If we use ImagePicker, we can delete the resized image after everything is done.

However, if we use CameraImagePicker, it will generate two files, the original image and the resized image. I can always delete the resized image after everything is done (so not to flood the storage as I don't need it anymore) but there is no way to delete the original image.

I think it should be configurable whether to keep the original photo or not after resize, if the photo is taken using camera picker.

**Comment by coomar2841** [comment]
Adding a temp file field in ```ChosenImage``` which can be used to delete any temp files that are generated.

**Comment by coomar2841** [comment]
Will be available in 1.1.2
