### ISSUE TITLE
Not able to select Multiple image

### ISSUE THREAD

**Issue by nirmal912** [coomar2841/android-multipicker-library#57]
imagePicker = new ImagePicker(this);
        imagePicker.setImagePickerCallback(this);
        imagePicker.allowMultiple();
        imagePicker.pickImage();

i am using this code and i have Samsung J1 with 4.4.4 OS its not able to select multiple image other than that its working on other devices.

**Comment by iori57** [comment]
I think the user have to select a picker that supports multiple selection, this isn't something that the library can control.

Refer to issue #39

**Comment by coomar2841** [comment]
It depends on whether the selected application can support multiple selections or not. So closing this issue.
