### ISSUE TITLE
Could not find com.kbeanie:multipicker:1.1.2

### ISSUE THREAD

**Issue by virengujariya** [coomar2841/android-multipicker-library#58]
Is 1.1.2 released yet? Gradle picks 1.1.1 but not 1.1.2
or probably temporary issue?

**Comment by jessexx** [comment]
It's not up on Maven Central yet it seems.  I'm also waiting on this update as it fixes a few issues I've been running into.

**Comment by coomar2841** [comment]
Ooops. Something went wrong. Publishing failed. Have published it again now. Should be up in an hour or so.

**Comment by jessexx** [comment]
Seems it's up now, and I was able to build it with gradle.  Thanks for the release!
