### ISSUE TITLE
Image File Name

### ISSUE THREAD

**Issue by NoelChew** [coomar2841/android-multipicker-library#6]
The filename used for saving images into new folder is based on the image name. Problem arises when two different images of the same name from two different folders gets saved into the folder. It will override the old image.
Another problem is if we use any image loader with caching mechanism, it will show old image instead of the new image.
I suggest to use timestamp as the name of the new image to prevent this problem.

**Comment by coomar2841** [comment]
This shouldn't happen. I am always checking if the file already exists or not. If it exists, it appends (1) to the file name. Are you sure it's not working as expected?

**Comment by NoelChew** [comment]
I am quite sure..

**Comment by coomar2841** [comment]
Ok. Will check it out. Thanks.

**Comment by coomar2841** [comment]
Fixed.

**Comment by NoelChew** [comment]
thanks Kumar!
