### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by ParitoshVaidya** [coomar2841/android-multipicker-library#61]
Getting following error after adding library:

Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed with multiple errors, see logs

I tried `gradle assemble -info` but it is taking too much time to finish.

**Comment by coomar2841** [comment]
Can you post logs please?

**Comment by ParitoshVaidya** [comment]
The command `gradle assemble -info` is not completing on my machine. 

Build process with following library is working correctly.

`compile 'com.kbeanie:image-chooser-library:1.5.8@aar'`

**Comment by coomar2841** [comment]
Possible for you to send me a sample project?

**Comment by ParitoshVaidya** [comment]
Created test project, and added all dependencies from existing project. I started getting error in new project. Removed dependency one by one and compiled project. 

Found that, after removing following dependency, build succeeded.

    compile 'es.guiguegon:gallerymodule:1.3.1'

**Comment by coomar2841** [comment]
Closing this.

**Comment by d-rahul** [comment]
Open application manifest(AndroidManifest.xml), click on the "Merged Manifest" tab next to the "Text" tab of the manifest file. You can view the error in the right column, try to solve the error and build again it will solve this error.
For error: https://readyandroid.wordpress.com/errorexecution-failed-for-task-appprocessdebugmanifest-manifest-merger-failed-with-multiple-errors-see-logs-android/
For more check: https://readyandroid.wordpress.com/
