### ISSUE TITLE
"onImagesChosen" callback method is not triggered 

### ISSUE THREAD

**Issue by maheswaranecemohan** [coomar2841/android-multipicker-library#63]
Kindly provide me support on this.

**Comment by coomar2841** [comment]
Can you post your code? How are you initializing the code. And also logs.

**Comment by maheswaranecemohan** [comment]
Logs:
---------------------------

11-08 12:29:50.199 16800-16800/com.philips.enicu D/ImagePickerImpl: Item [0]: content://com.android.providers.media.documents/document/image%3A44668
11-08 12:29:50.199 16800-16800/com.philips.enicu D/ImagePickerImpl: Item [1]: content://com.android.providers.media.documents/document/image%3A44667
11-08 12:29:50.199 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Before: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44668, Original Path: null, MimeType: null, Size: 0 B Height: 0, Width: 0, Orientation: UNDEFINED
11-08 12:29:50.219 16800-17028/com.philips.enicu D/mali_winsys: new_window_surface returns 0x3000,  [720x1280]-format:1
11-08 12:29:50.219 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Path: null
11-08 12:29:50.239 16800-16800/com.philips.enicu I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@374bc03 time:61700979
11-08 12:29:50.279 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: folder: Pictures
11-08 12:29:50.279 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: extension: null
11-08 12:29:50.279 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: mimeType: image/jpeg
11-08 12:29:50.279 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: type: image
11-08 12:29:50.279 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: Out Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09445-2.jpg
11-08 12:29:50.299 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Final Path: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44668, Original Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09445-2.jpg, MimeType: image/jpeg, Size: 1.7 MB Height: 0, Width: 0, Orientation: UNDEFINED
11-08 12:29:50.299 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Before: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44667, Original Path: null, MimeType: null, Size: 0 B Height: 0, Width: 0, Orientation: UNDEFINED
11-08 12:29:50.299 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Path: null
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: folder: Pictures
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: extension: null
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: mimeType: image/jpeg
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: type: image
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: copyFileToFolder: Out Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09444-3.jpg
11-08 12:29:50.339 16800-18181/com.philips.enicu D/FileProcessorThread: processFile: Final Path: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44667, Original Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09444-3.jpg, MimeType: image/jpeg, Size: 1.6 MB Height: 0, Width: 0, Orientation: UNDEFINED
11-08 12:29:50.339 16800-18181/com.philips.enicu D/ImageProcessorThread: postProcessImage: image/jpeg
11-08 12:29:50.689 16800-18181/com.philips.enicu D/ImageProcessorThread: postProcessImage: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44668, Original Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09445-2.jpg, MimeType: image/jpeg, Size: 1.7 MB Height: 1932, Width: 2576, Orientation: NORMAL
11-08 12:29:50.689 16800-18181/com.philips.enicu D/ImageProcessorThread: postProcessImage: image/jpeg
11-08 12:29:50.969 16800-18181/com.philips.enicu D/ImageProcessorThread: postProcessImage: Type: image, QueryUri: content://com.android.providers.media.documents/document/image%3A44667, Original Path: /storage/emulated/0/ENICU/ENICU Pictures/20161108_09444-3.jpg, MimeType: image/jpeg, Size: 1.6 MB Height: 1932, Width: 2576, Orientation: NORMAL
--------------------------------------------


Code:
---------------------------------
public class ObservationNewActivity extends AppCompatActivity implements ImagePickerCallback {
    private static final String TAG = makeLogTag(ObservationNewActivity.class);
    private static final String urlProfileImg = "http://www.imgion.com/images/01/very-very-happy-baby1.jpg";
    private ImageView mImg_profile_pic;
    //private MaterialBetterSpinner mSpinner_temperature;
    private Toolbar mToolbar;
    private ImagePicker mImagePicker;
    private CameraImagePicker mCameraPicker;
    private String mPickerPath;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_observation_new1);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        //mToolbar = (Toolbar)findViewById(R.id.toolbar);
        //initToolBar();
        mImg_profile_pic = (ImageView) findViewById(R.id.img_profile_pic);
        //mSpinner_temperature = (MaterialBetterSpinner) findViewById(R.id.spinner_temperature);
        String[] TEMPERATURE = getResources().getStringArray(R.array.temperature);
        ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_dropdown_item_1line, TEMPERATURE);
        //mSpinner_temperature.setAdapter(arrayAdapter);

        /*Glide.with(this).load(urlProfileImg)
                .crossFade()
                .thumbnail(0.5f)
                .bitmapTransform(new CircleTransform(this))
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(mImg_profile_pic);*/

        init();
    }

    private void init() {

        mImg_profile_pic.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                //pickImageMultiple();
                pickImageSingle();
            }
        });

    }

    public void pickImageSingle() {
        mImagePicker = new ImagePicker(this);
        mImagePicker.setFolderName("Random");
        mImagePicker.setRequestId(1234);
        mImagePicker.ensureMaxSize(500, 500);
        mImagePicker.shouldGenerateMetadata(true);
        mImagePicker.shouldGenerateThumbnails(true);
        mImagePicker.setImagePickerCallback(this);
        Bundle bundle = new Bundle();
        bundle.putInt("android.intent.extras.CAMERA_FACING", 1);
        mImagePicker.setCacheLocation(PickerUtils.getSavedCacheLocation(this));
        mImagePicker.pickImage();
    }

    public void pickImageMultiple() {
        mImagePicker = new ImagePicker(this);
        mImagePicker.setImagePickerCallback(this);
        mImagePicker.allowMultiple();
        mImagePicker.pickImage();
    }

    public void takePicture() {
        mCameraPicker = new CameraImagePicker(this);
        mCameraPicker.setCacheLocation(CacheLocation.INTERNAL_APP_DIR);
        mCameraPicker.setImagePickerCallback(this);
        mCameraPicker.shouldGenerateMetadata(true);
        mCameraPicker.shouldGenerateThumbnails(true);
        mPickerPath = mCameraPicker.pickImage();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        if (id == android.R.id.home) {
            onBackPressed();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == ObservationNewActivity.RESULT_OK) {
            if (requestCode == Picker.PICK_IMAGE_DEVICE) {
                if (mImagePicker == null) {
                    mImagePicker = new ImagePicker(this);
                    mImagePicker.setImagePickerCallback(this);
                }
                mImagePicker.submit(data);
            } else if (requestCode == Picker.PICK_IMAGE_CAMERA) {
                if (mCameraPicker == null) {
                    mCameraPicker = new CameraImagePicker(this);
                    mCameraPicker.setImagePickerCallback(this);
                    mCameraPicker.reinitialize(mPickerPath);
                }
                mCameraPicker.submit(data);
            }
        }
    }

    @Override
    public void onImagesChosen(List<ChosenImage> list) {
        Log.d("onImagesChosen--->" + list.size(), "");
        LogUtils.LOGD(TAG, "--->" + list.get(0).getOrientationName());
    }

    @Override
    public void onError(String s) {
        Log.d("onImagesChosen--->", s);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        // You have to save path in case your activity is killed.
        // In such a scenario, you will need to re-initialize the CameraImagePicker
        outState.putString("picker_path", mPickerPath);
        super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        // After Activity recreate, you need to re-intialize these
        // two values to be able to re-intialize CameraImagePicker
        if (savedInstanceState != null) {
            if (savedInstanceState.containsKey("picker_path")) {
                mPickerPath = savedInstanceState.getString("picker_path");
            }
        }
        super.onRestoreInstanceState(savedInstanceState);
    }


}
--------------------------------

**Comment by AFagbedji** [comment]
I had the same problem too. And I noticed that onActivityResult () was not fired at the back of the gallery, which led to the fact that onImagesChosen() is not triggered to turn.

**Comment by AFagbedji** [comment]
How can i do to solve my problem?

**Comment by AFagbedji** [comment]
I found the fault in my code, I had not called super.onActivityResult () in onActivityResult () of the host activity. when i add it, it solves my problem

**Comment by coomar2841** [comment]
Cool. Closing this now.
