### ISSUE TITLE
android error

### ISSUE THREAD

**Issue by yogeshvidh** [coomar2841/android-multipicker-library#65]
i want to show database in list view but below error show Fatal Exception: java.lang.RuntimeException: Unable to resume activity

package com.example.janmat;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Context;
import android.database.Cursor;
import android.database.DataSetObserver;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;
import android.widget.TextView;

public class ListViewActivity extends Activity {
	
	 public SQLiteDatabase db;
	 
	 public String name, add;
	 
	 Cursor cursor;
	 
	 
	 
	SQLiteListAdapter ListAdapter;
		
		 ArrayList<String> ID_ArrayList = new ArrayList<String>();
		 ArrayList<String> NAME_ArrayList = new ArrayList<String>();
		 
		 //private String DB_PATH = "/sdcard/Ringtones/";
		 
			//private static String DB_NAME = "bhushanDB.db";
			
			//String myPath=DB_PATH + DB_NAME;
		
		 ListView LISTVIEW;
	/*
	 * 
	 * SqlHelper Class
	 * 
	 */
	 
	 
	 
	
	
	
	
	/*
	 * 
	 * SQLAdapter Class
	 * 
	 */
	
	public class SQLiteListAdapter implements android.widget.ListAdapter{
	
	Context context;
	ArrayList<String> userID;
	 ArrayList<String> UserName;
	
	 public SQLiteListAdapter(
		Context context2,
		 ArrayList<String> name,
		 ArrayList<String> add)
{
	this.context = context2;
	this.userID = name;
	 this.UserName = add;
	 
}
public int getCount() {
// TODO Auto-generated method stub
return userID.size();
}
public Object getItem(int position) {
	 // TODO Auto-generated method stub
	 return null;
	 }
public long getItemId(int position) {
// TODO Auto-generated method stub
return 0;
}

public View getView(int position, View child, ViewGroup parent) {
	 
	 Holder holder;
	 LayoutInflater layoutInflater;
	 if (child == null) {
		 layoutInflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
		 child = layoutInflater.inflate(R.layout.listviewdatalayout, null);
		 holder = new Holder();
		 holder.textviewid = (TextView) child.findViewById(R.id.textViewID);
		 holder.textviewname = (TextView) child.findViewById(R.id.textViewNAME);
		 child.setTag(holder);
	 } else {	
		 holder = (Holder) child.getTag();
	 }
	 holder.textviewid.setText(userID.get(position));
	 holder.textviewname.setText(UserName.get(position));
	 return child;
}
public class Holder {
	TextView textviewid;
	 TextView textviewname;
}
@Override
public int getItemViewType(int arg0) {
	// TODO Auto-generated method stub
	return 0;
}
@Override
public int getViewTypeCount() {
	// TODO Auto-generated method stub
	return 0;
}
@Override
public boolean hasStableIds() {
	// TODO Auto-generated method stub
	return false;
}
@Override
public boolean isEmpty() {
	// TODO Auto-generated method stub
	return false;
}
@Override
public void registerDataSetObserver(DataSetObserver arg0) {
	// TODO Auto-generated method stub
	
}
@Override
public void unregisterDataSetObserver(DataSetObserver arg0) {
	// TODO Auto-generated method stub
	
}
@Override
public boolean areAllItemsEnabled() {
	// TODO Auto-generated method stub
	return false;
}
@Override
public boolean isEnabled(int arg0) {
	// TODO Auto-generated method stub
	return false;
}
	}
	

	 @Override
	 public void onCreate(Bundle savedInstanceState) {
	 super.onCreate(savedInstanceState);
	 setContentView(R.layout.activity_list);

	 LISTVIEW = (ListView) findViewById(R.id.listView1);

	 
	 
	 }

	 @Override
	 protected void onResume() {

	 ShowSQLiteDBdata() ;
	 
	 super.onResume();
	 }

	 private void ShowSQLiteDBdata() {
	 
		 db=openOrCreateDatabase("Hanuman", Context.MODE_PRIVATE, null);
	 
	 cursor = db.rawQuery("SELECT * FROM persons", null);

	 ID_ArrayList.clear();
	 NAME_ArrayList.clear();
	 
	 
	 if (cursor.moveToFirst()) {
	 do {
	 ID_ArrayList.add(cursor.getString(cursor.getColumnIndex(name)));
	 
	 NAME_ArrayList.add(cursor.getString(cursor.getColumnIndex(add)));
	 
	

	 } while (cursor.moveToNext());
	 }
	 
	 ListAdapter = new SQLiteListAdapter(ListViewActivity.this,
	 
	 ID_ArrayList,
	 NAME_ArrayList);
	 
	 LISTVIEW.setAdapter(ListAdapter);
	 	 cursor.close();
	 }
	}

**Comment by yogeshvidh** [comment]
help me

**Comment by coomar2841** [comment]
Sorry. This report is not related to this project. Closing.
