### ISSUE TITLE
Not able to choose multiple items in Samsung devices

### ISSUE THREAD

**Issue by mjmotani** [coomar2841/android-multipicker-library#67]
I have tried with note 4 and S5, both devices are having 6.0.1. Multiple item selection is not working in any of the image, video or audio.

**Comment by coomar2841** [comment]
It depends on the applications that are there. They probably don't support picking multiple items the usual way.

**Comment by mjmotani** [comment]
I was using the default Samsung gallery as image chooser...

**Comment by coomar2841** [comment]
Closing this.
