### ISSUE TITLE
NPE invoking ProviderInfo.loadXmlMetaData(PackageManager, String)

### ISSUE THREAD

**Issue by es0329** [coomar2841/android-multipicker-library#69]
Goal: capture image via camera.
Device: Google Nexus 6P
OS: Android 7.1.1, API 25

Exception at [line #95](https://github.com/coomar2841/android-multipicker-library/blob/dev/app/src/main/java/com/kbeanie/multipicker/sample/fragments/ImagePickerFragment.java#L95).

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                       at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                       at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                       at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:144)
                                                                       at com.kbeanie.multipicker.core.ImagePickerImpl.pick(ImagePickerImpl.java:120)
                                                                       at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:74)
```

Any clues are greatly appreciated.

**Comment by coomar2841** [comment]
Do you have an xml file named paths.xml in your resources folder? Could you give some more logs?

**Comment by coomar2841** [comment]
Can you post the code where you initialize the picker?

**Comment by es0329** [comment]
Yes, I have res/paths.xml. Also, the only calling logic is takeVideo() and I init right there just like the demo.

**Comment by es0329** [comment]
Lower API devices behave correctly with my logic, whether retrieving image or video, from gallery or capturing via camera.

API 24+ devices are able to pick image or video from gallery however they NPE crash when I attempt to capture image or video via camera.

**Comment by coomar2841** [comment]
Can you post the contents of the res/paths.xml file please. And also, a detailed log report.

**Comment by es0329** [comment]
Here are [both files](https://gist.github.com/es0329/c4cce002d5100196db76f50a2c2b5d14).

**Comment by coomar2841** [comment]
The XML seems to be an issue. For now, can you just rename this XML
file(paths.XML) to something else and see if it solves the problem. If it
does, I will fix this bug in the library, and you can go back to the paths
file name.

**Comment by es0329** [comment]
Ok, cool. Tried a couple different names for that file just now but I get same crash result.

**Comment by coomar2841** [comment]
As I understand you have your own file provider? Are you using
tools:override in the declaration?

On Dec 13, 2016 2:28 AM, "Eric" <notifications@github.com> wrote:

Ok, cool. Tried a couple different names for that file just now but I get
same crash result.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/coomar2841/android-multipicker-library/issues/69#issuecomment-266550591>,
or mute the thread

**Comment by es0329** [comment]
I've updated [the Gist](https://gist.github.com/es0329/c4cce002d5100196db76f50a2c2b5d14) with to show my provider's declaration `AndroidManifest.xml`.

**Comment by coomar2841** [comment]
Can you try this? Create a class extending FileProvider. And use that class name here? If that solves the issue for you, I will update the library to use a custom FileProvider.

**Comment by es0329** [comment]
Subclassing `FileProvider` to have a custom name seems to fix the issue on my end. Thanks for looking at this with me.

**Comment by coomar2841** [comment]
Great. Thanks for your bug report. In the next version, I will add a custom FileProvider so that the applications don't have to use a custom one.
