### ISSUE TITLE
android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by SolaBe** [coomar2841/android-multipicker-library#7]
When load image from Picassa gallery on android 4.1.2 application crash wit error:
android.os.NetworkOnMainThreadException
at com.kbeanie.multipicker.core.threads.ImageProcessorThread$1.run(ImageProcessorThread.java:49)
Uri returned in onActivityResult - content://com.sec.android.gallery3d.provider/picasa/item/5545697766928513266

**Comment by coomar2841** [comment]
Will check this.

**Comment by coomar2841** [comment]
Can you give me more logs?

**Comment by SolaBe** [comment]
This is log when i saw this error :
`Fatal Exception: android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1118)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at libcore.net.http.HttpConnection.<init>(HttpConnection.java:70)
       at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
       at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
       at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
       at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
       at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:315)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:461)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
       at com.olodroid.meme.fragments.FragmentUserTemplate$2.loadInBackground(FragmentUserTemplate.java:150)
       at com.olodroid.meme.fragments.FragmentUserTemplate$2.loadInBackground(FragmentUserTemplate.java:143)
       at com.olodroid.meme.fragments.FragmentUserTemplate.loadImageWithURL(FragmentUserTemplate.java:159)
       at com.olodroid.meme.fragments.FragmentUserTemplate.access$100(FragmentUserTemplate.java:54)
       at com.olodroid.meme.fragments.FragmentUserTemplate$1.onImagesChosen(FragmentUserTemplate.java:104)
       at com.kbeanie.multipicker.core.threads.ImageProcessorThread$1.run(ImageProcessorThread.java:49)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
`

I think the problem was in my code. I tried create bitmap from path 
`picture = BitmapFactory.decodeFile(path,options);` and when picture == null  i tried download bitmap 
`   private Bitmap loadImageWithURL(final String urlStr, final BitmapFactory.Options options) {
        AsyncTaskLoader<Bitmap> asyncTaskLoader = new AsyncTaskLoader<Bitmap>(getActivity()) {
            @Override
            public Bitmap loadInBackground() {
                Bitmap bmp = null;
                try {
                    URL url = new URL(urlStr);
                    HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
                    InputStream is = urlConnection.getInputStream();
                    bmp = BitmapFactory.decodeStream(is,new Rect(),options);
                    urlConnection.disconnect();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                return bmp;
            }
        };
        return asyncTaskLoader.loadInBackground();
    }`

I got exception on this line
`InputStream is = urlConnection.getInputStream();` 

I remove this method and now when i try load this image i get logs:
`03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:104)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:92)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:139)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcess(FileProcessorThread.java:127)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:103)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:75)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:38)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err: com.kbeanie.multipicker.api.exceptions.PickerException: java.io.FileNotFoundException: Source 'https:/lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg' does not exist
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:143)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcess(FileProcessorThread.java:127)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:103)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:75)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:38)
03-09 23:40:59.319 29611-874/com.olodroid.meme W/System.err: Caused by: java.io.FileNotFoundException: Source 'https:/lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg' does not exist
03-09 23:40:59.329 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:104)
03-09 23:40:59.329 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:92)
03-09 23:40:59.329 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:139)
03-09 23:40:59.329 29611-874/com.olodroid.meme W/System.err: 	... 4 more
03-09 23:40:59.329 29611-874/com.olodroid.meme W/System.err: java.io.FileNotFoundException: Source 'https:/lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg' does not exist
03-09 23:40:59.339 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:104)
03-09 23:40:59.349 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:92)
03-09 23:40:59.349 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:139)
03-09 23:40:59.349 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcess(FileProcessorThread.java:127)
03-09 23:40:59.349 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcessFiles(FileProcessorThread.java:116)
03-09 23:40:59.349 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:76)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:38)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err: com.kbeanie.multipicker.api.exceptions.PickerException: java.io.FileNotFoundException: Source 'https:/lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg' does not exist
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:143)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcess(FileProcessorThread.java:127)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.postProcessFiles(FileProcessorThread.java:116)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:76)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:38)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err: Caused by: java.io.FileNotFoundException: Source 'https:/lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg' does not exist
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:104)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.copyFile(FileUtils.java:92)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.copyFileToFolder(FileProcessorThread.java:139)
03-09 23:40:59.359 29611-874/com.olodroid.meme W/System.err: 	... 4 more
03-09 23:40:59.369 29611-874/com.olodroid.meme D/ImageProcessorThread: postProcessImage: image/jpeg
03-09 23:40:59.379 29611-874/com.olodroid.meme E/JHEAD: can't open 'https://lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg'
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err: java.lang.NullPointerException
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.getWidthOfImage(FileProcessorThread.java:680)
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.generateMetadata(ImageProcessorThread.java:83)
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImage(ImageProcessorThread.java:74)
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImages(ImageProcessorThread.java:62)
03-09 23:40:59.379 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:39)
03-09 23:40:59.379 29611-874/com.olodroid.meme E/JHEAD: can't open 'https://lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg'
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err: java.lang.NullPointerException
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.getHeightOfImage(FileProcessorThread.java:694)
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.generateMetadata(ImageProcessorThread.java:84)
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImage(ImageProcessorThread.java:74)
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImages(ImageProcessorThread.java:62)
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:39)
03-09 23:40:59.389 29611-874/com.olodroid.meme E/JHEAD: can't open 'https://lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg'
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err: com.kbeanie.multipicker.api.exceptions.PickerException: Error while generating thumbnail: 1 https://lh5.googleusercontent.com/-z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg
03-09 23:40:59.389 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.downScaleAndSaveImage(FileProcessorThread.java:664)
03-09 23:40:59.399 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.generateThumbnails(ImageProcessorThread.java:90)
03-09 23:40:59.399 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImage(ImageProcessorThread.java:77)
03-09 23:40:59.399 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImages(ImageProcessorThread.java:62)
03-09 23:40:59.399 29611-874/com.olodroid.meme W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:39)`

list.get(0).getOriginalPath() in onImagesChosen(List<ChosenImage> list) method return url 
https://lh5.googleusercontent.com/z4493ChCBA4/TPZIDItaO7I/AAAAAAAAAEU/AjenDecsBrY/I/85447.jpg

**Comment by coomar2841** [comment]
Is this a Samsung phone? There is an issue with Samsung phones. I have fixed it. You shouldn't have to write this much extra code for this. This will be fixed in **Version 0.9.7**.

**Comment by coomar2841** [comment]
Done.

**Comment by SolaBe** [comment]
Great, thank you.
