### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by guidedways** [coomar2841/android-multipicker-library#74]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
       at android.support.v4.content.FileProvider.parsePathStrategy(SourceFile:583)
       at android.support.v4.content.FileProvider.getPathStrategy(SourceFile:557)
       at android.support.v4.content.FileProvider.getUriForFile(SourceFile:399)
       at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(SourceFile:144)
       at com.kbeanie.multipicker.core.ImagePickerImpl.pick(SourceFile:120)
       at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(SourceFile:74)
       

On:

`cameraImageCaptureHandler = new CameraImagePicker(this);
    cameraImageCaptureHandler.setImagePickerCallback(this);
    cameraImageCaptureHandler.shouldGenerateThumbnails(false);
    cameraImageCaptureHandler.shouldGenerateMetadata(false);
    cameraPickingPath = cameraImageCaptureHandler.pickImage();`

**Comment by guidedways** [comment]
Seeing quite a lot of these come up in Crashlytics. I have no idea why it's crashing on pickImage.

**Comment by coomar2841** [comment]
Do you have your own FileProvider? Also, let me know which version you are using.

**Comment by guidedways** [comment]
1.1.3 (latest). I have a File provider but that's for something completely different - I don't use anything special with the Multi Picker. I simply want the user to be able to take a photo and then later extract it.

**Comment by coomar2841** [comment]
You can try this version ```1.1.3.2-snapshot```.

To verify. Check if taking a picture with camera is crashing on a Nougat device/emulator. IF it crashes, change the library version to the above version. And see if it solves the problem.

**Comment by guidedways** [comment]
Good one - yes it's only 7.0 and 7.1.1 :)

**Comment by coomar2841** [comment]
Did this solve the issue?

**Comment by guidedways** [comment]
I'll have to release it first as I haven't been able to reproduce this myself. Waiting for crashes to come through in a few days and will confirm, but I'm sure it might help given you knew exactly which OS version it may have been failing on 👍

**Comment by guidedways** [comment]
I can confirm I've stopped seeing this error in Fabric now after using the snapshot

**Comment by coomar2841** [comment]
Great. Closing this now.

**Comment by guidedways** [comment]
Is the fix included in 1.1.31?

**Comment by nsmirosh** [comment]
I'm seeing this issue still in 1.1.4-beta
