### ISSUE TITLE
Feature request: support GIF uploads

### ISSUE THREAD

**Issue by virengujariya** [coomar2841/android-multipicker-library#76]
Or will it be supported under FILE type?

**Comment by virengujariya** [comment]
Or will it be supported under FILE type?

**Comment by coomar2841** [comment]
Uploads? Can you please elaborate?

**Comment by virengujariya** [comment]
@coomar2841 I meant allowing to pick gif

**Comment by coomar2841** [comment]
Ok. Will check.

**Comment by virengujariya** [comment]
@coomar2841 I think it should be fine either ways.

**Comment by virengujariya** [comment]
Ohhh wait! I think it is already supported that way. :)

**Comment by coomar2841** [comment]
Closing this.
