### ISSUE TITLE
WRITE_EXTERNAL_STORAGE issue

### ISSUE THREAD

**Issue by tree1891** [coomar2841/android-multipicker-library#77]
I have tested camera picker on Sumsung phone.
In onError, it shows "WRITE_EXTERNAL_STORAGE permission not available".

**Comment by coomar2841** [comment]
Can you post the full logs?

**Comment by lolsheeplol** [comment]
It sounds like you have a permission issue, if you app has targetsdk 23+, you now need to grant runtime permissions for all of the "dangerous permissions" (such as camera, storage, contacts, etc).  More on it here https://developer.android.com/training/permissions/requesting.html

**Comment by tree1891** [comment]
`01-22 17:55:11.593 22726-22726/com.shaghalni.shaghalni W/System.err: com.kbeanie.multipicker.api.exceptions.PickerException: android.permission.WRITE_EXTERNAL_STORAGE permission not available
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.utils.FileUtils.getExternalFilesDirectory(FileUtils.java:35)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.core.PickerManager.getDirectory(PickerManager.java:137)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.core.PickerManager.buildFilePath(PickerManager.java:129)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:148)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.core.ImagePickerImpl.pick(ImagePickerImpl.java:121)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:81)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.shaghalni.shaghalni.Post3Fragment.onClickCapture(Post3Fragment.java:207)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.shaghalni.shaghalni.Post3Fragment$2$1.onMenuItemClick(Post3Fragment.java:152)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:108)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:346)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1577)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3970)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AbsListView.onTouchUp(AbsListView.java:6080)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AbsListView.onTouchEvent(AbsListView.java:5839)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:120)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.View.dispatchTouchEvent(View.java:10018)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2833)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5771)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2318)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.View.dispatchPointerEvent(View.java:10253)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5523)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5359)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4964)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5021)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7525)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7393)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7354)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7635)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:323)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.os.Looper.loop(Looper.java:135)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7406)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-22 17:55:11.603 22726-22726/com.shaghalni.shaghalni W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`
