### ISSUE TITLE
Multiple image picking does not work with Gallery

### ISSUE THREAD

**Issue by aislingvasey** [coomar2841/android-multipicker-library#78]
Version: compile 'com.kbeanie:multipicker:1.1.31@aar'

The multi picking of images only works from certain locations. 
For example: it works fine if I use Downloads or Recent as the source of the images. It does not work when using Gallery as it only allows 1 image to be picked. The usual Gallery picker allows multi images to be selected with a long press.
I guess the only difference is when using the Gallery it says Select Photo as the title so maybe there is some functionality to do with image vs photo?

Tested on various devices including Samsung (Android 6), LG  and Vodafone Smart (Android 5).

I see the same behaviour with your sample app on the Play Store.

**Comment by coomar2841** [comment]
Picking multiple images depends on the target application. Not all Galleries support it. Closing this.
