### ISSUE TITLE
Media Picker - receiving selected items path

### ISSUE THREAD

**Issue by surya329** [coomar2841/android-multipicker-library#83]
Hi,i have used your library and loaded media picker to load media where i can select multiple images or videos,how can i get the path of file selected if i select multiple items.On the activity result how can i get the values as a listpaths.

Finally thanks for creating an amazing library,great work.

**Comment by coomar2841** [comment]
Are you not getting those in the calback? ```onFileChosen()``` ?

**Comment by surya329** [comment]
Thanks for your time.Yes i dont recieve the file on Mediafilechosen().

Can you help me with some lines on whether how to receive it.

**Comment by coomar2841** [comment]
Can you post some log? Also, can you check if the sample app works for you?

**Comment by surya329** [comment]
okay sure i will look into it and get back to you.

**Comment by surya329** [comment]
hi i got the files onMediachosen() after getting a look into the sample thanks for the help.
