### ISSUE TITLE
Can not able to select multiple images/files from gallary and explorer

### ISSUE THREAD

**Issue by rupeshpadhye** [coomar2841/android-multipicker-library#85]
Hi ,
I tried sample app on the Xiaomi  Redmi 3S prime and not able attach multiple images/files. After selecting one image/file  , it is coming out of chooser .  
I am able to select multiple images from "photos option" but not from gallery and explorer.

**Comment by coomar2841** [comment]
This is a limitation of those apps which don't allow multiple selections from other apps. Sorry, no solution for this yet.
