### ISSUE TITLE
how to use this library in nougat

### ISSUE THREAD

**Issue by rahulsharma8545** [coomar2841/android-multipicker-library#87]
As we know that in android we cannot address direct path to any file. so how to use this library in android Nougat.
I want to select a video file from device and upload to server it is working below Nougat well. but in Nougat it does not returns the real path of file.
so how to use this in Nougat?
please notify soon

**Comment by coomar2841** [comment]
Can you give me logs? Also, can you try the sample application and see if it works?

**Comment by rahulsharma8545** [comment]
I was using a privious version of library, Now it's working thanks.

**Comment by Queskr** [comment]
We're using 1.1.31 and are get feedbacks that it doesn't work in Nougat. Did you test it in Nougat? Should we use a more advanced build?

**Comment by coomar2841** [comment]
Do you have any logs.
