### ISSUE TITLE
Minimum SDK too high

### ISSUE THREAD

**Issue by marcusmotill** [coomar2841/android-multipicker-library#9]
Is it possible to change the minimum SDK to something a bit older?  I would really love API 10!  Thanks for everything

**Comment by coomar2841** [comment]
Let me give it a try.

**Comment by marcusmotill** [comment]
Thanks, I want to add it to your new library to my app going live next week
so that would be clutch.

On Mon, Mar 14, 2016 at 1:05 AM Kumar Bibek <notifications@github.com>
wrote:

> Let me give it a try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coomar2841/android-multipicker-library/issues/9#issuecomment-196160446>
> .
>
-- 
Marcus Motill
University of Louisville
C: (561) 339-4465

**Comment by coomar2841** [comment]
Try out `0.9.8`

**Comment by marcusmotill** [comment]
Will do once released to the repo...thanks
