### ISSUE TITLE
Unable to get provider com.kbeanie.multipicker.utils.AMPFileProvider: 

### ISSUE THREAD

**Issue by burakkoray** [coomar2841/android-multipicker-library#90]
Hi 
Thanks for the great project
I was using 1.1.2 version that works great
After I tried to use 1.1.31 version I m getting issue(I wrote below) on some devices which android version lower than 4.4.2
Unable to get provider com.kbeanie.multipicker.utils.AMPFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.kbeanie.multipicker.utils.AMPFileProvider"

Could you look into this?
Thanks ...

**Comment by coomar2841** [comment]
Is this still an issue with the latest release?

**Comment by Parth20** [comment]
yes I get same issues in android 5.1 . can You please help me

**Comment by coomar2841** [comment]
Is your application breaching the dex limits? In that case, you need to have multi-dex enabled for your application.

**Comment by Parth20** [comment]
Hello dear friend ,
I have already done multipicker enabled true..
Currently i am using 1.1.4-beta  and it works ..
Is it ok or any issue remaining for this gradle version??

**Comment by coomar2841** [comment]
Cool. If it's working fine, you don't have to do anything.

**Comment by Parth20** [comment]
Sorry for mis spelling I have alrady enable multidex true..

email directly, view it on GitHub
<https://github.com/coomar2841/android-multipicker-library/issues/90#issuecomment-304779368>,
or mute the thread

**Comment by Parth20** [comment]
ok thnks ..
