### ISSUE TITLE
restrict mimetype for filepicker

### ISSUE THREAD

**Issue by urvish91** [coomar2841/android-multipicker-library#96]
Hi, how can we restrict specified multiple mimetype for file picker ? for ex. i want to allow only pdf, doc and txt file.

**Comment by coomar2841** [comment]
```java
filePicker.setMimeType("application/pdf");
```

This should work.

**Comment by urvish91** [comment]
Yes but I want to set multiple like doc and PDF only then how to do?

**Comment by coomar2841** [comment]
Sorry, there is no solution yet for this. Actually, it depends on the target applications. There is no recommended specification for handling multiple mime types.
