### ISSUE TITLE
Why do you copy videos?

### ISSUE THREAD

**Issue by Myeongwon-Kang** [coomar2841/android-multipicker-library#97]
Why do you copy videos?
Because of this, it is slow to choose a big video.

**Comment by SanyasiraoM** [comment]
@coomar2841 , Is there any chance for just to get paths of picked video or audio or image, instead of copying?

**Comment by Myeongwon-Kang** [comment]
I only need video path.
Is there a way?

**Comment by DrewCarlson** [comment]
@SanyasiraoM @Myeongwon-Kang https://github.com/coomar2841/android-multipicker-library/issues/29

**Comment by coomar2841** [comment]
Duplicate of #70 and #29 . Closing this.
